INSERT INTO user (id, user_name, password, user_id, created_at) values (1, 'sehun', '1234', 'tester', CURRENT_TIMESTAMP());
INSERT INTO user (id, user_name, password, user_id, created_at) values (2, 'dom', '1234', 'tester2', CURRENT_TIMESTAMP());

INSERT INTO notice (id, title, content, writer_id, created_at) values (1, '테스트입니다.', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (2, '테스트입니다. 2', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (3, '테스트입니다. 3', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (4, '테스트입니다. 4', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (5, '테스트입니다. 5', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (6, '테스트입니다. 6', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (7, '테스트입니다. 7', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (8, '테스트입니다. 8', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (9, '테스트입니다. 9', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (10, '테스트입니다. 10', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (11, '테스트입니다. 11', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (12, '테스트입니다. 12', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (13, '테스트입니다. 13', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (14, '테스트입니다. 14', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (15, '테스트입니다. 15', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (16, '테스트입니다. 16', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (17, '테스트입니다. 17', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (18, '테스트입니다. 18', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (19, '테스트입니다. 19', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (20, '테스트입니다. 20', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (21, '테스트입니다. 21', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (22, '테스트입니다. 22', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (23, '테스트입니다. 23', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (24, '테스트입니다. 24', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (25, '테스트입니다. 25', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (26, '테스트입니다. 26', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (27, '테스트입니다. 27', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (28, '테스트입니다. 28', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (29, '테스트입니다. 29', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (30, '테스트입니다. 30', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (31, '테스트입니다. 31', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (32, '테스트입니다. 32', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (33, '테스트입니다. 33', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (34, '테스트입니다. 34', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 2, CURRENT_TIMESTAMP());
INSERT INTO notice (id, title, content, writer_id, created_at) values (35, '테스트입니다. 35', '이것은 테스트입니다. 열심히 작성하지 않은 공지지요.', 1, CURRENT_TIMESTAMP());
